# Generates docs/config.js from .env (not committed).
# Usage: .\tools\generate_peymii_config.ps1

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$envFile = Join-Path $root ".env"
$outFile = Join-Path $root "docs\config.js"

function Get-EnvValue([string]$name) {
    if (-not (Test-Path $envFile)) { return $null }
    foreach ($line in Get-Content $envFile) {
        if ($line -match "^\s*#") { continue }
        if ($line -match "^\s*$name\s*=\s*(.+)\s*$") {
            return $Matches[1].Trim().Trim('"').Trim("'")
        }
    }
    return $null
}

$supabaseUrl = Get-EnvValue "SUPABASE_URL"
$anonKey = Get-EnvValue "SUPABASE_ANON_KEY"
$publicBase = Get-EnvValue "PUBLIC_STORE_BASE_URL"
if (-not $publicBase) { $publicBase = "https://bizmi.app" }

$basePath = Get-EnvValue "PEYMI_PAGES_BASE_PATH"
if (-not $basePath) { $basePath = "" }

$playUrl = Get-EnvValue "PLAY_STORE_URL"
if (-not $playUrl) {
    $playUrl = "https://play.google.com/store/apps/details?id=com.example.bakery_shop_app"
}

$appStoreUrl = Get-EnvValue "APP_STORE_URL"
if (-not $appStoreUrl) { $appStoreUrl = "" }

$androidPackage = Get-EnvValue "ANDROID_PACKAGE"
if (-not $androidPackage) { $androidPackage = "com.example.bakery_shop_app" }

if (-not $supabaseUrl -or -not $anonKey) {
    Write-Error "Missing SUPABASE_URL or SUPABASE_ANON_KEY in .env"
}

$js = @"
// Auto-generated by tools/generate_peymii_config.ps1 — do not commit.
window.PEYMI_CONFIG = {
  appName: "Peymii",
  publicBaseUrl: "$publicBase",
  basePath: "$basePath",
  supabaseUrl: "$supabaseUrl",
  supabaseAnonKey: "$anonKey",
  playStoreUrl: "$playUrl",
  appStoreUrl: "$appStoreUrl",
  androidPackage: "$androidPackage",
  deepLinkScheme: "bizmi",
  tryOpenAppFirst: true,
  redirectDelayMs: 1600,
};
"@

$js | Set-Content -Path $outFile -Encoding UTF8
Write-Host "Wrote $outFile"
